image:
  repository: madugula-ramakrishna/TechTrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 8095

livenessProbe:
  path: /healthz
  port: 8095

readinessProbe:
  path: /healthz
  port: 8095