namespace: sandbox

service:
  port: 7111
  targetPort: 7111
  protocol: TCP
  type: ClusterIP

image:
  repository: madugular/techtrends
  tag: v2
  pullPolicy: Always

replicaCount: 3

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

containerPort: 4111

livenessProbe:
  path: /healthz
  port: 4111

readinessProbe:
  path: /healthz
  port: 4111
