namespace: staging

service:
  port: 3111
  targetPort: 3111
  protocol: TCP
  type: NodePort

image:
  repository: madugular/techtrends
  tag: v2
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    memory: 90Mi
    cpu: 300m
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111
