namespace: sandbox

service:
  port: 8091
  targetPort: 8095
  protocol: TCP
  type: ClusterIP

image:
  repository: madugular/TechTrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

containerPort: 8095

livenessProbe:
  path: /healthz
  port: 8095

readinessProbe:
  path: /healthz
  port: 8095
